apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd
spec:
  description: "{{ .Values.project.name }} applications"
  sourceRepos:
    {{- toYaml .Values.project.sourceRepos | nindent 4 }}
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
