name: test-zizmor
on: push
jobs:
  zizmor:
    permissions:
      contents: read
      security-events: write
    uses: github.com/Damien-Petit-Thomas/homelab-ci-templates/.github/workflows/zizmor.yml@main
